[package]
name = "vodozemac-hs"
version = "0.0.1"
authors = ["ners <ners@gmx.ch>"]
edition = "2021"

[lib]
name = "vodozemac_hs"
crate-type = ["staticlib"]

[dependencies]
serde_json = "1.0.132"
vodozemac = "0.8.1"
